theme: jekyll-theme-cayman

title: Jason Keighley
description: Student on the United Kingdom Research Institure's Centre of Doctoral training for Medical Diagnosis and Care at the University of Leeds.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

social_links:
  github:
    profile_url:
      https://github.com/Jjk422
  linked_in:
    profile_url:
      https://uk.linkedin.com/in/jjk422
  twitter:
    profile_url:
      https://mobile.twitter.com/jjk422
  ORCID:
    profile_url:
      https://orcid.org/0000-0002-3647-0683

navigation_bar_documents:
  - title: Home
    url: index.html

  - title: About Me
    url: about.html

  #  - title: CDT MSc project
  #    url: cdt_msc_project.html

  - title: CDT PhD project
    url: cdt_phd_project.html

#  - title: Posts
#    url: posts.html

  #  - title: Current methods and research
  #    url: cdt_phd_project.html

  #  - title: Publication History
  #    url: cdt_phd_project.html