theme: jekyll-theme-cayman

title: Profile - Jason Keighley
description: This site includes details on the student Jason Keighley.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

social_links:
  github:
    profile_url:
      https://github.com/Jjk422
  linked_in:
    profile_url:
      https://uk.linkedin.com/in/jjk422
  twitter:
    profile_url:
      https://mobile.twitter.com/jjk422
  ORCID:
    profile_url:
      https://orcid.org/0000-0002-3647-0683

